name: Renovate

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *" # Every 5 minutes

permissions:
  contents: write
  pull-requests: write
  issues: write
  security-events: read
  packages: read

jobs:
  renovate:
    name: Run Renovate
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v43.0.6
        with:
          configurationFile: .github/renovate-global.json
          token: ${{ secrets.GITHUB_TOKEN }}
